apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: f5-hello-world-web
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    secretName: cafe-secret
  rules:
  - host: 8d78df34-3fb9-4e77-8450-ca061eaf4dba.access.udf.f5.com
    http:
      paths:
      - path: /
        backend:
          serviceName: f5-hello-world-web
          servicePort: 8080
